#!/usr/bin/env bash
# DevBridge — Port availability checker
# Writes .env with the first available port for each service
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

detect_lan_ip() {
  if command -v ip >/dev/null 2>&1; then
    local route_ip
    route_ip=$(ip route get 1.1.1.1 2>/dev/null | awk '/src/ {for (i=1; i<=NF; i++) if ($i=="src") {print $(i+1); exit}}')
    if [[ -n "${route_ip}" ]]; then
      echo "${route_ip}"
      return
    fi
  fi

  if command -v hostname >/dev/null 2>&1; then
    local host_ip
    host_ip=$(hostname -I 2>/dev/null | awk '{print $1}')
    if [[ -n "${host_ip}" ]]; then
      echo "${host_ip}"
      return
    fi
  fi

  echo "127.0.0.1"
}

find_free_port() {
  local start=$1
  local port=$start
  while ss -tulpn 2>/dev/null | grep -q ":$port "; do
    port=$((port + 1))
  done
  echo "$port"
}

AGENT_PORT=$(find_free_port 3333)
PWA_PORT=$(find_free_port 5173)
AGENT_HOST=$(detect_lan_ip)

ENV_FILE="$ROOT/.env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/check-ports.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AGENT_PORT=${AGENT_PORT}
PWA_PORT=${PWA_PORT}
# Host LAN IP used by the mobile app to reach the agent directly
AGENT_HOST=${AGENT_HOST}
# JWT secret — change in production
JWT_SECRET=$(openssl rand -hex 32)
# Workbox / Push VAPID keys (regenerate with: npx web-push generate-vapid-keys)
VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=
VAPID_EMAIL=mailto:devbridge@localhost
# Relay MVP — future public product path
RELAY_PORT=4444
RELAY_PUBLIC_URL=http://localhost:4444
RELAY_INTERNAL_URL=http://relay:4444
RELAY_JWT_SECRET=
# Volume mount: path to your project on the host
PROJECT_ROOT=${HOME}/projects
EOF

echo "✓ Ports assigned — Agent: ${AGENT_PORT}  PWA: ${PWA_PORT}"
echo "✓ .env written to ${ENV_FILE}"
echo ""
echo "Next: run 'npm run vapid' in agent/ to generate VAPID keys, then fill them into .env"
